### ISSUE TITLE
Ad revenue paid event are not being catched in applovin callback function

### ISSUE THREAD

**Issue by Artsiom17** [AppLovin/AppLovin-MAX-Defold#4]
**MAX SDK Version**
AppLovin-MAX-Defold 1.0.0

**build.gradle configuration:**
```
repositories {
    google()
    mavenCentral()
    maven { url "https://android-sdk.is.com" }
    maven { url "https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea" }
}

dependencies {
    implementation 'com.applovin:applovin-sdk:+'
    implementation 'com.applovin.mediation:fyber-adapter:+'
    implementation 'com.applovin.mediation:google-adapter:+'
    implementation 'com.applovin.mediation:inmobi-adapter:+'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'com.applovin.mediation:ironsource-adapter:+'
    implementation 'com.applovin.mediation:vungle-adapter:+'
    implementation 'com.applovin.mediation:facebook-adapter:+'
    implementation 'com.applovin.mediation:mintegral-adapter:+'
    implementation 'com.applovin.mediation:unityads-adapter:+'
    implementation 'com.google.android.gms:play-services-ads:22.5.0'
}
```

**Applovin initialization:**
   ```
    applovin.set_callback(applovin_callback)
    applovin.set_verbose_logging_enabled(true)
    applovin.set_user_id("ID")
    applovin.initialize("KEY")
```

**Catch applovin callbacks:**
```
local function applovin_callback(self, name, params)
    print(name)
    pprint(params)
end
```
**Problem description:**
Applovin sdk was successfully initialized with correct keys and ids. Banners, interstitials and rewarded can be shown as expected. I n _applovin_callback_ function i can catch majority of events, such as load, display, failed, hidden of banner, interstitial and rewarded events. But I can't catch no one from revenue paid event :

- OnBannerAdRevenuePaidEvent
- OnRewardedAdRevenuePaidEvent
- OnInterstitialAdRevenuePaidEvent

**Expected behaviour:**
_applovin_callback_ function should catch ad revenue paid events

**Comment by wootaejeon** [comment]
@Artsiom17 Thanks for reporting the issue. Plugin [v1.1.0](https://github.com/AppLovin/AppLovin-MAX-Defold/releases/tag/release_1_1_0) is now live which contains the fix for the issue.
