### ISSUE TITLE
Audio stuttering on iPhone after playing ad

### ISSUE THREAD

**Issue by dri-richard** [AppLovin/AppLovin-MAX-Defold#9]
(NB: I could only reproduce this issue using live ads, not test ads. This makes sense, as the test ad has no audio)

After playing an ad on iPhone, the game audio becomes distorted.
This can be easily reproduced in the example project:
- Add a sound component to the game object in main.collection
- Choose an .ogg file in the sound component
- Set the sound to loop

Screen recording that shows the problem:
https://github.com/AppLovin/AppLovin-MAX-Defold/assets/26457985/fe180885-80ff-4518-ab42-f48fef55cdc8

**Comment by wootaejeon** [comment]
Hi @dri-richard, thanks for reporting the issue. Does the sound gets distorted every time you load an ad with sound?

**Comment by dri-richard** [comment]
Not every time, but it's frequent, maybe 50% of the time.
5 different people on my team have seen it on different phones - iPhone 13, 13 mini, 15 Pro etc.
One person said they couldn't reproduce the issue on their iPhone SE 2020. It could be related to iOS version.

**Comment by wootaejeon** [comment]
@dri-richard I would suggest stopping the sound right before showing the ad (so that only the sound from the ad plays for its duration) and resume on `OnRewardedAdHiddenEvent` callback. Could you try that out and see if it helps?

**Comment by dri-richard** [comment]
I was trying to test this last week but unfortunately, because I needed to test with live ads (test ads have no audio), it's caused our account to be suspended and nobody has responded to our request to restore it.

**Comment by dri-richard** [comment]
From my point of view this issue isn't stale, but I'm not able to contribute further due to account suspension.

**Comment by dri-richard** [comment]
@thomasmso it's Rare Pets - https://apps.apple.com/gb/app/rare-pets-merge-game-mystery/id1566162104 / https://play.google.com/store/apps/details?id=com.drihq.pets
